# Generated by Django 4.1.7 on 2023-04-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ATCdash', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
